version: '2'
services:
  coturn:
    image:  dreamnetwork/coturn:4.4.5.3
    entrypoint: ["/usr/bin/turnserver", "-n", "-a", "-v", "--use-auth-secret", "--realm=demo", "--static-auth-secret=kaazshared", "--rest-api-separator=:"]
  broker:
    image: kaazing/3rd-party:activemq-5.10.0
  kaazing.example.com:
    build: gateway
    ports:
      - "443:443"
      - "3478:3478"
      - "3478:3478/udp"
    environment:
    - GATEWAY_OPTS=-Dfeature.turn.proxy -Dfeature.turn.rest
